### ISSUE TITLE
(Suggestion) when using the Dark theme in devtools, it to also apply to the embedded (CodeMirror) script editor

### ISSUE THREAD

**Issue by darkred** [greasemonkey/greasemonkey#2666]
Using GM 4.0 in FF 57.0

My suggestion is. when using the 'Dark' theme in Firefox's devtools _(the default is the 'Light')_, 
it to also apply to the embedded (CodeMirror) script editor.
_And, maybe in such case, to use the syntax highlighting that Firefox's Scratchpad uses?_

I'm suggesting this because, in GM 4.0 it's no longer possible to edit user scripts in an external editor,
and, as I find 'light' themes straining and annoying for the eyes, I try to avoid them as much as possible.
(for reference, the external editors I use are Sublime Text and VSCode, and both use a dark theme by default)

Thank you

**Comment by arantius** [comment]
What's the WebExt API that would let us know what theme you've set for dev tools?

**Comment by Sxderp** [comment]
This, I think?
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/devtools.panels/themeName

**Comment by garry-ut99** [comment]
I'm not sure what has been fixed there given the issue has been closed as completed, but the Dark Mode feature discussed here doesn't work: enabling Dark Mode in Firefox dev tools doesn't bring Dark Mode to Greasmonkey script editor.

**Comment by adamhotep** [comment]
**Client-side implementation**

Here is a full implementation of dark mode that you can apply through your `userContent.css` file without waiting for an update to Greasemonkey:

```css
/* Greasemonkey */
@-moz-document url-prefix("moz-extension://1382b313-768d-4d6e-cd79-88530b7cf52d/") {

  /* Editor: Softer tab background (edit-user-script.html) */
  #tabs .tab { background-color: #b2b2b2 !important; }

  /* Enable dark mode by user preference, key on it to invert most GM pages */
  :root { color-scheme: light dark; }
  @media ( prefers-color-scheme: dark ) {

    /* Invert the whole document, correct colors, undo (double-invert) images */
    html, img { filter: invert() hue-rotate(180deg); }

    /* Backup Import: color-scheme did the work for us (backup/import.html) */
    @-moz-document url-prefix("moz-extension://1382b313-768d-4d6e-cd79-88530b7cf52d/src/content/backup") {
      html, img { filter: none; }
    }

    /* EVERYTHING COLOR IS INVERTED! (except images) */
    /* Invert a color w/ JS: `(0xb2b2b2 ^ 0xffffff).toString(16)` == "4d4d4d" */

    /* Toolbar menus: grayer background, stronger border (monkey-menu.html) */
    /* (sadly, --toolbar-bgcolor and --toolbar-color are unset here) */
    #mobile-wrapper :is(section, textarea) { background: #ddd !important; }
    #mobile-wrapper :is(section, textarea, span) { color: #000 !important; }
    #mobile-wrapper textarea:not(:focus) { border: 1px solid #bbb !important; }

    /* Editor: Softer code background and colors (edit-user-script.html) */
    div#editor > div.CodeMirror, .CodeMirror-gutters, #tabs .tab.active, #save {
      background-color: #e7e5e4 !important;
    }
    div#editor > div.CodeMirror { filter: saturate(75%); }
  }

}
```

Your [userContent.css file](https://superuser.com/a/319322/300293 "How can I override the CSS of a site in Firefox with userContent.css?") lives in your profile's `chrome` directory. If it does not exist, you'll have to create it. Once it exists (and you've restarted Firefox), you can edit it from within Firefox using the Style Editor in Developer Tools (press <kbd>F12</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> or its Mac equivalent).

Since the UUID changes for each install, you'll have to edit (or create) a userscript in Greasemonkey and copy the URL's hyphenated hexadecimal code into the *two* `url-prefix` entries above.

This identifies Greasemonkey pages (including the toolbar menu) and, solely when the user has selected a dark theme (for the titlebar menus) or dark mode (for content), tweaks their CSS, most notably inverting the colors on most of the pages, then correcting the hue back to the initial colors (otherwise color emojis would also be inverted). Images are inverted back. 

The toolbar menu was too dark with a pure black background, so I lightened it to `#222` (the inversion of `#ddd`). Text colors are pushed back to `#fff` (inverted `#000`). The text input borders seemed to vanish, so I reinforced them.

The editor was IMHO too contrasted, so I softened the background from pure black to `#181a1b` (inverted `#e7e5e4`) and desaturated the code editor.

**Comment by adamhotep** [comment]
While @arantius can certainly just apply these to the relevant CSS files, it's probably better to update [shoelace](https://github.com/shoelace-style/shoelace), which added dark theme support between 1.x-beta and 2.0.0-beta (~2021). However, that may be a larger can of worms. What I've done should be sufficient.

I'll leave this ticket closed since I am not including a pull request. Hopefully this represents an easy path forward to add dark mode to Greasemonkey.

**Comment by garry-ut99** [comment]
> adamhotep : Here is a full implementation of dark mode that you can apply through your `userContent.css` file without waiting for an update to Greasemonkey:

Tested: works on Windows 7 SP1, but not on Windows 10 22H2.
Didn't try on Android so far yet, they say it should work, but requires root: [LINK](https://www.reddit.com/r/firefox/comments/vkgqvf/is_it_possible_to_add_css_user_styles_in_firefox/)

> adamhotep : The editor

The style coloring is very good in the editor. 


However toolbar menu font doesn't look good with lower screen gammas (like 0.75) (and higher gamma than 0.75 makes my screen too bright, that's why I have set it to 0.75):

>  adamhotep : The text input borders seemed to vanish, so I reinforced them.

- unfortunately both white (active scripts names) and greyed out (inactive scripts names) fonts, are still too washed / vanished out with gamma like 0.75
- also when hovering mouse over them, the background highlight is too dark (barely visible) with gamma like 0.75

In comparison, Firefox extensions menu (after clicking Jigsaw puzzle button) doesn't suffer any of the above issues (even with 0.75 screen gamma). Maybe you could fine-tune your style to fix the both issues to not happen on lower gammas.

Thx anyway.

**Comment by adamhotep** [comment]
@garry-ut99: I do not have a Windows system to test with, but on my Linux system, I tested this with 0.500 and 0.7500 gamma to try to reproduce what you're seeing, and I could not reproduce your issue. Could you provide screenshots?

As you can see from the CSS above, I didn't change much, just a color inversion and some minor tweaks, so theoretically this should be easy to fix if the light theme is legible on your display. Maybe try changing the `#mobile-wrapper` color values from `#ddd` and `#bbb` to `#fff` to be higher contrast. This refers to the menu, not anything for Android. (I haven't tried this on Android and you provided a compelling reason not to 😉)

**Comment by garry-ut99** [comment]
> Adamhotep: Maybe try changing the `#mobile-wrapper` color values from `#ddd` and `#bbb` to `#fff` to be higher contrast.

Didn't work.

> Adamhotep: Could you provide screenshots?

Yes (if you still don't see it on the screenshoot, you might still need to decerase gamma of your screen). 
As seen, on my screen, on gamma 0.75: 
- row highlight is invisible
- scroll bar is invisible
- text is washed out and malformed
- some letters partialy or even completely invisible

![Image](https://github.com/user-attachments/assets/43ae3628-4472-4c1f-be63-0db8908083a5)

**Comment by adamhotep** [comment]
@garry-ut99: When I turn my gamma down to 0.75, my view of your screenshot at 0.75 replicates what you're talking about, but I can't replicate it in Firefox until I turn my gamma down to 0.40. Scrollbars differ by the OS and toolkit (I'm on Linux with GTK) and cannot be skinned afaik.

In the event you haven't already done this, I highly suggest calibrating your display and its gamma correction using a guide like the [Lagom LCD test](http://www.lagom.nl/lcd-test/gamma_calibration.php).

If you've calibrated as far as you can (or as far as you're willing), I believe you can sort your issue with the following three additional lines below the other `#mobile-wrapper` lines in userContent.css:

```css
    #mobile-wrapper { --focus-color:#aaa; }
    #mobile-wrapper :is(section menuitem.go-back:hover, menuitem:focus .text) { text-shadow:0 0 1ex #fff; }
    #mobile-wrapper menuitem.disabled { opacity:0.8!important; text-decoration:line-through; }
```

This increases the contrast and abandons the opacity-driven defaults in favor of hard colors for focus and for differentiating disabled menu items. I kept a little in the disabled item but those items are now distinguishable with a notable strike-through effect. I also added a text shadow to increase the contrast of the focus color. It is much more visible on my setup at 0.40 gamma and not garishly high-contrast at 1.00 gamma. In fact, given the original opacity trick, it's about the same (barring the strike-through).
